name: full stack
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      testRepo:
        description: 'location'
        required: false
      solutionRepo:
        description: 'location'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    name: ${{ github.event.inputs.name }}
    steps:
    - uses: actions/checkout@v2
    - name: Run challenge (Node.js ${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clone tests repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.testRepo }}
        path: ./challenge
    - name: Install dependencies
      run: npm ci
      working-directory: ./challenge
    - name: Clone app repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.solutionRepo }}
        path: ./_cloned-app
    - name: Install solution client dependencies
      run: npm ci
      working-directory: ./_cloned-app/client
    - name: Init client solution
      run: npm run init
      working-directory: ./_cloned-app/client
      continue-on-error: true
    - name: Install solution server dependencies
      run: npm ci
      working-directory: ./_cloned-app/server
    - name: Init server solution dependencies
      run: npm run init
      working-directory: ./_cloned-app/server
      continue-on-error: true
    - name: Start server solution dependencies
      run: npm start
      working-directory: ./_cloned-app/server
      continue-on-error: true
    - name: Run solution client dependencies
      run: npm start & npx wait-on http://localhost:3000
      working-directory: ./_cloned-app/client
    - name: Run test on cloned app
      run: npm run test
      working-directory: ./challenge
